### ISSUE TITLE
ModuleNotFoundError: No module named 'core.config'

### ISSUE THREAD

**Issue by JXKZMJ** [gt0day/AnonGT#3]
`python3 AnonGT.py    `           

error 
                    
_**Traceback (most recent call last):
  File "/root/TOOLS/AutoTool/AnonGT/AnonGT.py", line 2, in <module>
    from core.config.functions import check_root, listToString, clear
ModuleNotFoundError: No module named 'core.config'**_

**Comment by gt0day** [comment]
1) install first "sudo bash install.sh" then close terminal
2) open new terminal and run "sudo anongt"
